#!/usr/bin/env python3
"""Generate docs/GAP_CLOSURE.md, docs/STATUS.md and docs/VALIDATOR.md.

Sources: docs/gaps.yaml (gap ledger) and aeris_comp.validation.CATALOG. Every total and
percentage is computed here; nothing in the generated files is hand-edited.

    python scripts/generate_docs.py           # write
    python scripts/generate_docs.py --check   # fail if any generated file is stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import _bootstrap  # noqa: F401
import yaml

from aeris_comp.validation import CATALOG

REPO = Path(__file__).resolve().parents[1]
LEDGER = REPO / "docs" / "gaps.yaml"

STATUSES = (
    "UNKNOWN", "BLOCKED", "VERIFIED", "IMPLEMENTED", "LOCALLY_TESTED",
    "HARNESS_TESTED", "MEASURED", "REFUTED", "NOT_APPLICABLE", "CLOSED",
)  # fmt: skip
CLOSED = {"VERIFIED", "LOCALLY_TESTED", "HARNESS_TESTED", "MEASURED", "REFUTED", "NOT_APPLICABLE", "CLOSED"}
DIMENSIONS = ("COMPLIANCE", "HARNESS", "ENGINEERING", "BENCHMARK", "EXPERIMENT", "OPTIMIZATION", "RESEARCH", "PAPER", "RELEASE")
FIELDS = (
    "id", "dimension", "area", "gap", "authority", "previous", "action",
    "evidence", "test", "status", "blocker", "resolution", "mandatory",
)  # fmt: skip
HEADER = "<!-- Generated by scripts/generate_docs.py from {source}. Do not edit by hand. -->\n\n"


class LedgerError(ValueError):
    pass


def load_ledger(path: Path = LEDGER) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    seen = set()
    for gap in data["gaps"]:
        missing = [f for f in FIELDS if f not in gap]
        if missing:
            raise LedgerError(f"{gap.get('id', '?')}: missing fields {missing}")
        if gap["id"] in seen:
            raise LedgerError(f"duplicate id {gap['id']}")
        seen.add(gap["id"])
        if gap["status"] not in STATUSES:
            raise LedgerError(f"{gap['id']}: unknown status {gap['status']!r}")
        if gap["dimension"] not in DIMENSIONS:
            raise LedgerError(f"{gap['id']}: unknown dimension {gap['dimension']!r}")
        if gap["status"] == "BLOCKED" and gap["blocker"] in ("", "-"):
            raise LedgerError(f"{gap['id']}: BLOCKED needs a blocker")
        if gap.get("human_action") and gap["status"] != "BLOCKED":
            raise LedgerError(f"{gap['id']}: human_action is only meaningful while BLOCKED")
    return data


def pct(num: int, den: int) -> str:
    return f"{100 * num / den:.1f}%" if den else "n/a"


def stats(gaps: list[dict]) -> dict:
    total = len(gaps)
    closed = sum(g["status"] in CLOSED for g in gaps)
    blocked = sum(g["status"] == "BLOCKED" for g in gaps)
    return {
        "total": total,
        "closed": closed,
        "blocked": blocked,
        "open": total - closed - blocked,
        "verifiable": total - blocked,
        "pct_verifiable": pct(closed, total - blocked),
        "pct_all": pct(closed, total),
    }


def cell(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_gap_closure(data: dict) -> str:
    gaps = data["gaps"]
    s = stats(gaps)
    counts = Counter(g["status"] for g in gaps)
    out = [HEADER.format(source="docs/gaps.yaml"), "# Gap closure ledger\n\n"]
    out.append(f"Last reviewed: {data['last_reviewed']}. Items: {s['total']}.\n\n")
    out.append(
        "Closed means VERIFIED, LOCALLY_TESTED, HARNESS_TESTED, MEASURED, REFUTED, NOT_APPLICABLE or CLOSED. "
        "IMPLEMENTED (code exists, no evidence yet) and UNKNOWN (open) are not closed. "
        "Authority is the level in the hierarchy: 1 HARNESS_README, 2 sample_submission, "
        "3 official schemas and evaluation code, 4 Kaggle pages, 5 datasets, 6 ADK, 7 our code, 8 our assumption.\n\n"
    )
    out.append("## Totals\n\n| Status | Count | Share |\n| --- | ---: | ---: |\n")
    for status in STATUSES:
        if counts.get(status):
            out.append(f"| {status} | {counts[status]} | {pct(counts[status], s['total'])} |\n")
    out.append(f"| **Total** | **{s['total']}** | 100.0% |\n\n")
    out.append(
        f"Closed: {s['closed']} of {s['total']} ({s['pct_all']}); "
        f"{s['closed']} of {s['verifiable']} currently verifiable items ({s['pct_verifiable']}); "
        f"{s['blocked']} BLOCKED.\n\n"
    )
    columns = ("ID", "Area", "Gap", "Authority", "Previous status", "Required action", "Evidence", "Test", "Current status", "Blocker", "Resolution")
    keys = ("id", "area", "gap", "authority", "previous", "action", "evidence", "test", "status", "blocker", "resolution")
    for dimension in DIMENSIONS:
        rows = [g for g in gaps if g["dimension"] == dimension]
        if not rows:
            continue
        out.append(f"## {dimension}\n\n| " + " | ".join(columns) + " |\n|" + " --- |" * len(columns) + "\n")
        for g in rows:
            values = [cell(g[k]) for k in keys]
            if g["mandatory"]:
                values[0] = f"{values[0]}*"
            out.append("| " + " | ".join(values) + " |\n")
        out.append("\n")
    out.append("`*` marks mandatory items.\n")
    return "".join(out)


def render_status(data: dict) -> str:
    gaps = data["gaps"]
    s = stats(gaps)
    mandatory_blocked = [g for g in gaps if g["mandatory"] and g["status"] == "BLOCKED"]
    out = [HEADER.format(source="docs/gaps.yaml"), "# Project status\n\n"]
    out.append(f"Last reviewed: {data['last_reviewed']}.\n\n")
    out.append(
        f"**{s['pct_verifiable']} of currently verifiable requirements closed "
        f"({s['closed']}/{s['verifiable']}); {len(mandatory_blocked)} mandatory items blocked** "
        "by missing official artifacts (HARNESS_README, sample_submission, dataset: Kaggle access), "
        "the competition harness with a Gemma 4 endpoint, or a Kaggle account. "
        f"Counting blocked items, {s['closed']} of {s['total']} ({s['pct_all']}) are closed.\n\n"
    )
    out.append("| Dimension | Items | Closed | Open | Blocked | Closed / verifiable | Closed / all |\n")
    out.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n")
    for dimension in DIMENSIONS:
        d = stats([g for g in gaps if g["dimension"] == dimension])
        out.append(f"| {dimension} | {d['total']} | {d['closed']} | {d['open']} | {d['blocked']} | {d['pct_verifiable']} | {d['pct_all']} |\n")
    out.append(f"| **All** | {s['total']} | {s['closed']} | {s['open']} | {s['blocked']} | {s['pct_verifiable']} | {s['pct_all']} |\n\n")
    human = [g for g in gaps if g.get("human_action")]
    out.append("## Blockers that need a human\n\n")
    out.append("These cannot be automated (Kaggle login, rules acceptance, upload). Steps: [HUMAN_HANDOFF.md](HUMAN_HANDOFF.md). Everything else that is blocked depends on them.\n\n")
    for g in human:
        out.append(f"- {g['id']} ({g['dimension']}): {g['gap']}. Action: {g['human_action']}.\n")
    if not human:
        out.append("None.\n")
    out.append("\n## Mandatory blocked items\n\n")
    for g in mandatory_blocked:
        out.append(f"- {g['id']} ({g['dimension']}): {g['gap']}. Blocked by: {g['blocker']}.\n")
    open_items = [g for g in gaps if g["status"] in {"IMPLEMENTED", "UNKNOWN"}]
    out.append("\n## Open items that are not blocked\n\n")
    for g in open_items:
        out.append(f"- {g['id']} ({g['status']}): {g['gap']}. Next: {g['action']}.\n")
    if not open_items:
        out.append("None.\n")
    out.append("\nFull ledger: [GAP_CLOSURE.md](GAP_CLOSURE.md).\n")
    return "".join(out)


def render_validator() -> str:
    out = [HEADER.format(source="aeris_comp/validation.py CATALOG"), "# Validator issue codes\n\n"]
    out.append(
        "- **ERROR**: invalid under an OFFICIAL rule (Kaggle pages; HARNESS_README once available) or rejected by "
        "ADK's own parser/loader (google-adk 2.9.2). The harness is expected to reject the submission.\n"
        "- **WARNING**: risky, UNVERIFIED against the harness, or OUR POLICY. `blocking` policy warnings stop "
        "`build_submission.py` and `validate_submission.py` (use `--official-only` to ignore them).\n"
        "- **INFO**: harmless observation.\n\n"
        "The validator is never stricter than the official rules without saying so: tests assert that no "
        "POLICY or UNVERIFIED code is an ERROR (`tests/test_validator_levels.py`).\n\n"
    )
    counts = Counter((r.level, r.basis) for r in CATALOG.values())
    out.append("| Level | Basis | Codes |\n| --- | --- | ---: |\n")
    for (level, basis), n in sorted(counts.items()):
        out.append(f"| {level} | {basis} | {n} |\n")
    out.append(f"| | **Total** | **{len(CATALOG)}** |\n\n")
    out.append("| Code | Level | Basis | Blocking |\n| --- | --- | --- | --- |\n")
    order = {"ERROR": 0, "WARNING": 1, "INFO": 2}
    for code, rule in sorted(CATALOG.items(), key=lambda kv: (order[kv[1].level], kv[1].basis, kv[0])):
        out.append(f"| `{code}` | {rule.level} | {rule.basis} | {'yes' if rule.blocking else ''} |\n")
    return "".join(out)


def outputs() -> dict[Path, str]:
    data = load_ledger()
    return {
        REPO / "docs" / "GAP_CLOSURE.md": render_gap_closure(data),
        REPO / "docs" / "STATUS.md": render_status(data),
        REPO / "docs" / "VALIDATOR.md": render_validator(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != text:
            stale.append(path.relative_to(REPO).as_posix())
            if not args.check:
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print(f"stale generated docs: {stale}; run python scripts/generate_docs.py", file=sys.stderr)
        return 1
    print(("checked" if args.check else "generated") + (f" (updated {stale})" if stale and not args.check else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
