#!/usr/bin/env python3
"""Build paper tables from scored run directories (never from hand-typed numbers).

    python scripts/make_tables.py artifacts/runs/<B0 run> artifacts/runs/<FULL run> ... \
        --baseline B0 --out research/paper/tables

Each run directory needs manifest.json (from run_experiment.py prepare) and
records.jsonl (from run_experiment.py score). Writes main_results.md and
failure_categories.md. Exits non-zero if no run has records.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import _bootstrap  # noqa: F401

from aeris_comp.metrics import paired_comparison, summarize


def load_run(run_dir: Path) -> dict | None:
    records_path = run_dir / "records.jsonl"
    manifest_path = run_dir / "manifest.json"
    if not records_path.is_file() or not manifest_path.is_file():
        return None
    records = [json.loads(line) for line in records_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not records:
        return None
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    return {"dir": run_dir, "variant": manifest["variant"], "manifest": manifest, "records": records, "summary": summarize(records)}


def main_results_table(runs: list[dict], baseline: str | None) -> str:
    base = next((r for r in runs if r["variant"] == baseline), None)
    lines = [
        "| Variant | Tasks | PASS | PASS rate | 95% CI (Wilson) | vs baseline: +/- tasks | McNemar p | Submission SHA256 |",
        "| --- | ---: | ---: | ---: | --- | --- | ---: | --- |",
    ]
    for run in runs:
        s = run["summary"]
        lo, hi = s["pass_rate_ci95"]
        delta, p = "-", "-"
        if base is not None and run is not base:
            cmp = paired_comparison(base["records"], run["records"])
            delta = f"+{len(cmp['only_b_pass'])} / -{len(cmp['only_a_pass'])}"
            p = f"{cmp['mcnemar_exact_p']:.3f}"
        lines.append(
            f"| {run['variant']} | {s['n_tasks']} | {s['n_pass']} | {s['pass_rate']:.3f} | "
            f"[{lo:.3f}, {hi:.3f}] | {delta} | {p} | `{run['manifest'].get('submission_sha256', '')[:12]}` |"
        )
    return "\n".join(lines) + "\n"


def failure_table(runs: list[dict]) -> str:
    categories = sorted({c for r in runs for c in r["summary"]["failure_categories"]})
    header = "| Category | " + " | ".join(r["variant"] for r in runs) + " |"
    lines = [header, "| --- |" + " ---: |" * len(runs)]
    for category in categories:
        lines.append(f"| {category} | " + " | ".join(str(r["summary"]["failure_categories"].get(category, 0)) for r in runs) + " |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("runs", type=Path, nargs="*")
    parser.add_argument("--baseline", default="B0")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "research" / "paper" / "tables")
    args = parser.parse_args(argv)
    runs = [r for r in (load_run(d) for d in args.runs) if r is not None]
    if not runs:
        print("no scored runs given; tables are only generated from real records", file=sys.stderr)
        return 1
    note = "<!-- Generated by scripts/make_tables.py from: " + ", ".join(r["dir"].name for r in runs) + " -->\n\n"
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "main_results.md").write_text(note + main_results_table(runs, args.baseline), encoding="utf-8")
    (args.out / "failure_categories.md").write_text(note + failure_table(runs), encoding="utf-8")
    print(f"wrote {args.out / 'main_results.md'} and failure_categories.md from {len(runs)} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
